export type DeviceColor = {
  id: string;
  label: string;
  frame: string;
  frameColors?: string[];
  screen: string;
};

export type ShadowConfig = {
  enabled: boolean;
  color: string;
  blur: number;
  offsetX: number;
  offsetY: number;
};

export type DeviceSpec = {
  id: string;
  label: string;
  width: number;
  height: number;
  screenInset: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
  cornerRadius: number;
  frameRadius: {
    outer: string;
    inner: string;
  };
  notchWidth: number;
  notchHeight: number;
  hasIsland: boolean;
  colors: DeviceColor[];
};

export type GradientPreset = {
  id: string;
  label: string;
  from: string;
  to: string;
};

export type ImageOverlay = {
  id: string;
  src: string;
  x: number;
  y: number;
  width: number;
  height: number;
  layer: "behind" | "front";
  rotation: number;
  shadow: ShadowConfig;
};

export type DeviceStyle = "flat" | "3d";

export type DeviceInstance = {
  id: string;
  deviceId: string;
  colorId: string;
  screenshotSrc: string | null;
  x: number;
  y: number;
  scale: number;
  rotation: number;
  shadow: ShadowConfig;
  style: DeviceStyle;
  rotateY: number;
  rotateX: number;
};

export type Screenshot = {
  id: string;
  headline: string;
  subheadline: string;
  backgroundColor: string;
  backgroundMode: "solid" | "gradient" | "image";
  gradientPresetId: string | null;
  textColor: string;
  headlineX: number;
  headlineY: number;
  headlineWidth: number;
  subheadlineX: number;
  subheadlineY: number;
  subheadlineWidth: number;
  fontFamily: string;
  overlayImages: ImageOverlay[];
  devices: DeviceInstance[];
  activeDeviceId: string;
  /**
   * Free-form gradient set by AI suggestion or other future flow. When
   * present (and backgroundMode === "gradient"), wins over gradientPresetId.
   * Cleared when the user picks a preset.
   */
  customGradient?: { from: string; to: string } | null;
  /**
   * One-line description of what the uploaded screenshot shows
   * (e.g. "the home dashboard with daily streaks"). Auto-populated by the
   * vision AI flow when a screenshot image is set, used as context in every
   * subsequent AI prompt for this screenshot. Manual override OK.
   */
  screenDescription?: string;
  /**
   * Data URL used when backgroundMode === "image". Set by the AI image-gen
   * flow (Nano Banana Pro / GPT Image via Codex). Rendered as a cover-sized
   * background behind everything.
   */
  backgroundImageSrc?: string;
  /**
   * Background image opacity 0–1, default 1. Lets the user fade an
   * AI-generated background toward the backgroundColor so headlines/devices
   * stay readable.
   */
  backgroundImageOpacity?: number;
  /**
   * When true this panel renders as a "hero" — devices are hidden, text
   * gets larger default sizing, the background image gets to breathe.
   * Generated by the Hero panel flow; can also be toggled on any panel.
   */
  isHero?: boolean;
};

export type SelectedElement = {
  type: "headline" | "subheadline" | "image" | "device";
  screenshotId: string;
  id?: string;
};

export type ExportSize = {
  id: string;
  label: string;
  width: number;
  height: number;
};

/**
 * Platform variants a project can target. A single "app" (e.g. FoodyMerge)
 * is represented as multiple linked Project rows — one per platform — sharing
 * the same `groupId` and `groupName`.
 */
export type PlatformKey =
  | "ios-phone"
  | "ios-tablet"
  | "macos"
  | "android-phone"
  | "android-tablet"
  | "android-tablet-7";

/**
 * Project type - groups screenshots together
 */
export type Project = {
  /** Unique project identifier */
  id: string;
  /** Project name */
  name: string;
  /** Creation timestamp */
  createdAt: number;
  /** Last update timestamp */
  updatedAt: number;
  /** Screenshots belonging to this project */
  screenshots: Screenshot[];
  /** Selected device ID for this project */
  selectedDeviceId: string;
  /** Selected device color ID */
  selectedColorId: string;
  /** Export size ID */
  exportSizeId: string;
  /** Active screenshot ID */
  activeScreenshotId: string;
  /** Headline font size */
  headlineFontSize: number;
  /** Subheadline font size */
  subheadlineFontSize: number;
  /** Optional AI / brand context configuration. */
  ai?: AIProjectConfig;
  /**
   * Shared id linking platform-variant siblings. Projects with the same
   * `groupId` are different platforms of the same app.
   */
  groupId?: string;
  /**
   * Display name of the parent group (e.g. "FoodyMerge"). Project `name`
   * itself is per-variant (e.g. "FoodyMerge — iPhone").
   */
  groupName?: string;
  /** Which platform this variant targets. */
  platform?: PlatformKey;
  /**
   * Target locale key (from LOCALES). Absent = source / original language.
   * Set by "Duplicate as language", which clones a project and AI-translates
   * its copy. Locale variants are siblings (same `groupId`) of their source.
   */
  locale?: import("../constants").LocaleKey;
};

/**
 * Per-project AI configuration. Persisted alongside the rest of the project
 * so brand context follows the project across sessions and devices.
 */
export type AIProjectConfig = {
  /** Active provider for this project. Falls back to "claude" if absent. */
  provider?: "claude" | "codex" | "gemini";
  /** App name / brand name. */
  brandName?: string;
  /** Who is this for, in one line. */
  audience?: string;
  /** Voice/tone description (e.g. "playful, irreverent, copywriting like Apple"). */
  voice?: string;
  /** Single line summarizing the app's core feature. */
  keyFeature?: string;
  /**
   * Absolute path to a project/brand folder the user has consented to read
   * from. When set, Prestige scans a fixed list of brand-relevant files and
   * injects them into AI prompts. Tauri-only.
   */
  brandFolderPath?: string;
  /**
   * Last-used image-generation model. Remembered per project so the modal
   * defaults to whatever the user picked last time.
   */
  imageModel?: "nano-banana-pro" | "codex-gpt-image";
};
